# Generated by Django 2.1.4 on 2019-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef_distance_to_citycenter', models.FloatField()),
                ('coef_distance_to_airport', models.FloatField()),
                ('coef_distance_to_station', models.FloatField()),
                ('coef_year_built', models.FloatField()),
                ('coef_num_room', models.FloatField()),
                ('coef_num_bed', models.FloatField()),
                ('coef_num_bath', models.FloatField()),
                ('coef_living_area', models.FloatField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='houses',
            name='year_built',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='year'),
        ),
    ]
