# Generated by Django 2.1.4 on 2019-01-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190122_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='intercept',
            field=models.FloatField(default=0),
        ),
    ]
