# Generated by Django 2.1.4 on 2019-01-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_train_intercept'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='rmse',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='train',
            name='intercept',
            field=models.FloatField(),
        ),
    ]
